### ISSUE TITLE
Injected page variables don't get persisted

### ISSUE THREAD

**Issue by lonvarscsak** [tynamo/tapestry-conversations#2]
Hey there,

Whenever I inject a page into another page, and set instance variables into the new page, those variables do not get persisted.  Because at that moment in time there is no active conversation.

If I create the conversation in pageLoaded, the very first request to that page (when pageLoaded is called) works properly, because the conversation is created before any values get passed to it.  On subsequent new page requests don't persist the value.

Other than that one time, I can't think of how to get them to persist.  Any variables modified after the conversation is activated work fine.

Any thoughts?

Thanks,

Lon

P.S. -- I'm using more than one conversation, so that I can track changes in multiple windows.

**Comment by kaosko** [comment]
Perhaps I'm missing something more complex (and I have a feeling you know this already), but for basics the concept is conversation-within-page, i.e. you have to be "on the conversation scope" already to be able to persist to that conversation scope. For multiple conversations at the same, the conversation id is carried with the page context. Soo.. setting new instance variables from a different page will just not work because even if you were able to create a conversation before setting those variables, the system wouldn't be able to find that conversation again (that's why in the example in the guide, we causing a redirect after creating a conversation). If you have an initial state you need to set the conversation to, I'd pass the state as a context in the first page request, create conversation from that state and then redirect to the active conversation.

**Comment by lonvarscsak** [comment]
Yeah, I see what you're saying.  I guess it's just odd for me that things are marked as persist into a conversation, but don't get persisted into that...but that's probably just the nature of the beast.

Since at the point of time I'm doing this, I know that it's a new conversation...I just don't know what hook to use to create it at the appropriate time.  

I'll keep digging.  Thanks.
